name: Deploy Slides to GitHub Pages

on:
  push:
    branches: [main]  # Change to your source branch
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Pandoc
      uses: pandoc/setup-pandoc@v1
      with:
        pandoc-version: 'latest'
        texlive: 'none'

    - name: Convert Markdown to HTML
      run: |
        pandoc -d defaults.yaml -o index.html index.md

    - name: Create output directory
      run: mkdir -p output

    - name: Move generated files
      run: |
        mv index.html output/
        mv custom.css output/
        # Add any additional assets (CSS, images, etc.) to output/ here

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output