name: Deploy MkDocs to gh-pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

env:
  PYTHON_VERSION: '3.11'
  BUILD_DIR: site

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install MkDocs and plugins
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs==1.* mkdocs-material mkdocs-awesome-pages-plugin
          # If you have a requirements.txt:
          # pip install -r requirements.txt

      - name: Build
        run: mkdocs build --strict

      - name: Add .nojekyll
        run: |
          touch "${{ env.BUILD_DIR }}/.nojekyll"

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ${{ env.BUILD_DIR }}
          clean: true
          single-commit: true
